### ISSUE TITLE
Translation from XAML code does not work

### ISSUE THREAD

**Issue by cris-m** [CrossGeeks/MultilingualPlugin#17]
From this example.
```
<ContentPage
    x:Class="BasicXamarin.Localization.LocalisationPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:i18n="clr-namespace:BasicXamarin.Localization.Helper"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="Language App"
    FlowDirection="{x:Static Device.FlowDirection}"
    mc:Ignorable="d">
    <ContentPage.Content>
        <StackLayout Margin="10">
            <Label
                LineBreakMode="WordWrap"
                Text="{i18n:Translate HelloWorld}"
                VerticalOptions="Center" />
            <Picker
                x:Name="PickerLanguages"
                ItemDisplayBinding="{Binding DisplayName}"
                ItemsSource="{Binding Languages}"
                VerticalOptions="Center" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
``` i18n:Translate ``` doesnot translate the resource

**Comment by MobilyteApps** [comment]
@cris-m:- Hi  is there any luck, i am fetching this issue in Android,

**Comment by cris-m** [comment]
Currently the plugin has been deprecated. Now you have to use xamarin forms.

**Comment by Char0394** [comment]
Please check this post 
https://xamgirl.com/handle-multilingual-in-xamarin-forms-without-any-plugin/

**Comment by MobilyteApps** [comment]
@Char0394 can i uses plugin.multilingual?
But what will be the used  instead of TranslateExtension because as given your URL the TranslateExtension Need to be removed.

**await Xamarin.Forms.Application.Current.MainPage.DisplayAlert(TranslateExtension.GetText("Alert"), ex.Message, TranslateExtension.GetText("Ok"));**

**Comment by Char0394** [comment]
@MobilyteApps you can continue using it if you want.
Also, you can still use the Translate extension without the plugin.

You have 2 options:
- Continue using the Translate Extension without the plugin
- Continue using the Translate Extension with the plugin 
- Don't use the Translate Extension and instead add the text of the .resx file directly. (Check this part of article -- 3. Use your AppResources file in your code--)

**Comment by MobilyteApps** [comment]
@Char0394:- 
Hi, My Resource file is attached, By default its showing English but it can not converted to spanish,
i followed all steps as mentioned in URL

[Resources.zip](https://github.com/CrossGeeks/MultilingualPlugin/files/4685672/Resources.zip)

**Comment by MobilyteApps** [comment]
**@Char0394:-** I am using Visual Studio Version 16.6.0 and remove plugin.multilingual from project but i am getting no error but the language can not changed.

**Comment by Char0394** [comment]
If you are using visual studio for mac and you are having issues changing the language, there is an issue reported, and also a solution adding some lines in the android .csproject file to fix it. Check it here https://github.com/xamarin/xamarin-android/issues/4664#issuecomment-632986668

**Comment by MobilyteApps** [comment]
@Char0394 :- Hi, I am using Visual Studio Version 16.6.0 not MAC and I have add the android .csproject 

<Target Name="_ResolveSatellitePaths"
    DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference
        AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)"
        AssemblyFiles="@(ResolvedUserAssemblies)"
        AutoUnify="$(AutoUnifyAssemblyReferences)"
        FindDependencies="True"
        FindRelatedFiles="False"
        FindSatellites="True"
        SearchPaths="$(AssemblySearchPaths)"
        TargetFrameworkMoniker="$(TargetFrameworkMoniker)"
        TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)"
        TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths"/>
    </ResolveAssemblyReference>
  </Target>

and also add the line into assemblyInfo.cs

-- My By default is Spansih so Spanish is coming but not english is coming when i change the language:-

I put both es and en but no luck.
[assembly: NeutralResourcesLanguage("es", UltimateResourceFallbackLocation.Satellite)]

**Comment by MobilyteApps** [comment]
@Char0394 :- Hi, I am using Visual Studio Version 16.6.0 not MAC and I have add the lines into  android .csproject

<Target Name="_ResolveSatellitePaths"
    DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference
        AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)"
        AssemblyFiles="@(ResolvedUserAssemblies)"
        AutoUnify="$(AutoUnifyAssemblyReferences)"
        FindDependencies="True"
        FindRelatedFiles="False"
        FindSatellites="True"
        SearchPaths="$(AssemblySearchPaths)"
        TargetFrameworkMoniker="$(TargetFrameworkMoniker)"
        TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)"
        TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths"/>
    </ResolveAssemblyReference>
  </Target>

and also add the line into assemblyInfo.cs

-- My By default is Spansih so Spanish is coming but not english is coming when i change the language:-

I put both es and en but no luck.
[assembly: NeutralResourcesLanguage("es", UltimateResourceFallbackLocation.Satellite)]
