### ISSUE TITLE
C# usage?

### ISSUE THREAD

**Issue by IeuanWalker** [CrossGeeks/MultilingualPlugin#4]
How to use this plugin in c#?

**Comment by ali-h2010** [comment]
This might help
https://stackoverflow.com/questions/46477416/xamarin-forms-localization-in-code-behind

**Comment by Alibesharat** [comment]
here you can add this method in TranslateExtension Class :
` public string GetTranslate(string Text)
        {
            var ci = CrossMultilingual.Current.CurrentCultureInfo;
            return resmgr.Value.GetString(Text, ci);
        }
`
