### ISSUE TITLE
Does not properly work on iOS

### ISSUE THREAD

**Issue by joakimmag** [CrossGeeks/MultilingualPlugin#8]
## Bug Information

Version Number of Plugin: 1.0.2
Device Tested On: iPhone 8 Plus and Nexus 5X
Simulator Tested On: iPhone 5 / 7 Plus / 8 Plus, Android 8.1 / 9
Version of VS: 15.8.4 and 16.2.5
Version of Xamarin: 3.2 and 4.2
Versions of other things you are using:

### Steps to reproduce the Behavior

1. Install on PCL and Device projects.
2. Set phone/simulator language to English.
3. In `App.xaml.cs`, set a breakpoint:

```cs
protected override async void OnInitialized()
{
    InitializeComponent();
    Debugger.Break();
}
```

### Expected Behavior

`CrossMultilingual.Current.CurrentCultureInfo` should return English culture info.

### Actual Behavior

On Android, does as expected.
On iPhone, returns Norwegian culture info.

Mac Build Host language is English, and the development machine (Windows) is Norwegian.

**Comment by mharrisonbit** [comment]
I only get "en" no matter what the language or region I set on the device

**Comment by joakimmag** [comment]
Closing, as plugin has become deprecated.
